### ISSUE TITLE
Where do I download the example data?

### ISSUE THREAD

**Issue by kerkelae** [quin-med-harvard-edu/pyGRASP#2]
As a part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4865), I would like to ask for a clarification on how to [run the code on raw data](https://github.com/quin-med-harvard-edu/pyGRASP#demo). Where can I download the example data and what do I need to change in the mentioned files?

**Comment by curtcorum** [comment]
https://github.com/quin-med-harvard-edu/pyGRASP/blob/main/MRU.csv

There does not appear to be a valid link to any externally stored datafile for the demo?

**Comment by curtcorum** [comment]
Is the data needed for Figure 2 results (two datasets?) available?

**Comment by cariyurek** [comment]
You may download the dataset from [Figshare](https://figshare.com/articles/dataset/DCE_MRI_MRU_dat/20465637) and this is the data for Figure 2. You need to change '.csv' file to locate the data as described in README.md. Please do not hesitate to comment in this thread if you have further questions.

**Comment by emdupre** [comment]
Hi @cariyurek , thank you for this clarification !

Looking at the [demo](https://github.com/quin-med-harvard-edu/pyGRASP#demo) in the README, the data availability is not immediately obvious as the figshare link renders as:

```
Download the data figshare[@Ariyurek2022figshare]
```

Could you please update this to include a resolvable hyperlink ?

**Comment by cariyurek** [comment]
> Hi @cariyurek , thank you for this clarification !
> 
> Looking at the [demo](https://github.com/quin-med-harvard-edu/pyGRASP#demo) in the README, the data availability is not immediately obvious as the figshare link renders as:
> 
> ```
> Download the data figshare[@Ariyurek2022figshare]
> ```
> 
> Could you please update this to include a resolvable hyperlink ?

**Comment by cariyurek** [comment]
Hi @emdupre ,

Thank you for pointing this out. I have updated the "figshare" as a resolvable link.

**Comment by curtcorum** [comment]
Just a comment:

Is it possible to have a much reduced dataset for a demo?

11.33GB or even 4.55GB is (on the order of) the full sizes used...

To verify the code is works should take a much reduced dataset, and such large datasets represent a barrier to trying the code, especially if behind a low bandwidth link.
